# step 1 : importing the libraries

In [1]:
%pip install numpy
%pip install pandas
%pip install matplotlib
%pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://hpe-aruba-dev-jfrog-ro:****@aruba.jfrog.io/aruba/api/pypi/pypi-local/simple
Requirement already satisfied: numpy in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (2.2.6)
WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/manojravikumar/.pyenv/versions/3.10.0/bin/python3.10 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Looking in indexes: https://pypi.org/simple, https://hpe-aruba-dev-jfrog-ro:****@aruba.jfrog.io/aruba/api/pypi/pypi-local/simple
Requirement already satisfied: pandas in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/manojravikumar/.pyenv/versions/3.10.0/bin/python3.10 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Looking in indexes: https://pypi.org/simple, https://hpe-aruba-dev-jfrog-ro:****@aruba.jfrog.io/aruba/api/pypi/pypi-local/simple
Requirement already satisfied: matplotlib in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (3.10.6)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: pillow>=8 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: numpy>=1.23 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: contourpy>=1.0.1 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: fonttools>=4.22.0 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (25.0)
Requirement already satisfied: cycler>=0.10 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: six>=1.5 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/manojravikumar/.pyenv/versions/3.10.0/bin/python3.10 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Looking in indexes: https://pypi.org/simple, https://hpe-aruba-dev-jfrog-ro:****@aruba.jfrog.io/aruba/api/pypi/pypi-local/simple
Requirement already satisfied: scikit-learn in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (1.7.1)
Requirement already satisfied: scipy>=1.8.0 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: joblib>=1.2.0 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: numpy>=1.22.0 in /Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages (from scikit-learn) (2.2.6)
WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/manojravikumar/.pyenv/versions/3.10.0/bin/python3.10 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# step 2 : Reading the dataset

In [4]:
df = pd.read_csv(filepath_or_buffer='/Users/manojravikumar/Downloads/algoacademy.ai/loan_prediction_dataset.csv')
df.head()

   Age  Annual_Income  Credit_Score  Loan_Amount
0   58          47334           661        17589
1   48          43844           692        17458
2   34          67695           658        26552
3   27          36526           589        18967
4   40          62521           702        25274

# Step 3 : Seperating the Features and Target

In [13]:
X=df[["Age","Annual_Income","Credit_Score"]]
X

y=df["Loan_Amount"]
y

0     17589
1     17458
2     26552
3     18967
4     25274
      ...
95    27413
96    27837
97    19444
98    21303
99    27393
Name: Loan_Amount, Length: 100, dtype: int64

# Step 4 : Splitting the dataset into training set and test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y , random_state=104,test_size=0.25, shuffle=True)

# Step 5 : Creating the Model

In [22]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# Step 6 : Training the Model

In [23]:
model.fit(X_train,y_train)

LinearRegression()

# Step 7 : Testing the Model

In [28]:
y_pred = model.predict(X_test)
y_pred

array([25180.54529214, 26967.93209064, 18184.92473448, 26271.8266995 ,
       20816.97964399, 19593.52727802, 23398.62731096, 21502.1518598 ,
       17649.37825352, 19957.93652183, 23165.79926078, 24239.04059115,
       21996.90430766, 15235.89321262, 19615.85125167, 17928.05264264,
       18762.76626728, 29521.23723807, 21662.60536235, 20395.48811654,
       17249.24454541, 20605.25062428, 24222.20628656, 21071.86883087,
       18559.82133062])

In [31]:
df1 = X_test.copy()
df1["Actual_Loan_Amount"] = y_test
df1["Predicted_Loan_Amount"] = y_pred

df1.head()

    Age  Annual_Income  Credit_Score  Actual_Loan_Amount  Predicted_Loan_Amount
23   31          61155           654               26347           25180.545292
2    34          67695           658               26552           26967.932091
22   52          38161           786               16151           18184.924734
27   47          67372           698               26065           26271.826700
53   21          43510           662               21827           20816.979644

In [35]:
model.predict([[30,50000,422]])

/Users/manojravikumar/.pyenv/versions/3.10.0/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([18361.29787878])